### ISSUE TITLE
update database

### ISSUE THREAD

**Issue by n0rthf4ce** [tlo015/CoderBay#1]
// Whenever a user clicks the submit-bid button

// prevent form from submitting with event.preventDefault() or returning false

// Get the input values

// Log the Bidder and Price (Even if not the highest)

// If Then statements to compare against previous high bidder

// Alert that they are High Bidder

// Save the new price in Firebase

// Log the new High Price

// Store the new high price and bidder name as a local variable (could have also used the firebase variable)

// Change the HTML to reflect the new high price and bidder

// Else tell user their bid was too low via alert

**Comment by celsooliveiraTBDE** [comment]
// Whenever a user clicks the submit-bid button

// prevent form from submitting with event.preventDefault() or returning false

// Get the input values

// Log the Bidder and Price (Even if not the highest)
